String matchData = """[
    {
        "id": 40334,
        "matchCode": null,
        "clubHome": {
            "id": 699,
            "position": 0,
            "clubName": {
                "id": 15,
                "codeClub": "NEW",
                "name": "Newcastle United",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fnewcastle.png?alt=media&token=6bafa6f8-b79c-401d-bac3-231485e74cb5",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "St. James Park",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FNewcastle.jpg?alt=media&token=2a9fd582-7aaa-46cc-847f-689c55813d3f",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 15
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 15,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "clubAway": {
            "id": 706,
            "position": 0,
            "clubName": {
                "id": 1,
                "codeClub": "BOU",
                "name": "Bournemouth",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fbou.png?alt=media&token=9cd2d6ea-0f81-4ae8-8785-04b749442ed3",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Vitality Stadium",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FBournemouth.jpg?alt=media&token=70c35a2f-81b2-4043-9bb3-d308e2924638",
                    "active": 1,
                    "capacity": "",
                    "address": "",
                    "pitchSize": "",
                    "description": "",
                    "id": 1
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 1,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "matchDay": "2023-10-14",
        "matchTime": "22:01",
        "season": {
            "seasonname": "2022/23",
            "champion": null,
            "active": 1,
            "activeUI": 1,
            "id": 33
        },
        "roundmatch": 1,
        "leg": "first",
        "resultClubHome": null,
        "resultClubAway": null,
        "stadiumId": {
            "name": "St. James Park",
            "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FNewcastle.jpg?alt=media&token=2a9fd582-7aaa-46cc-847f-689c55813d3f",
            "active": 1,
            "capacity": null,
            "address": null,
            "pitchSize": null,
            "description": null,
            "id": 15
        },
        "referees": null,
        "active": 1
    },
    {
        "id": 40335,
        "matchCode": null,
        "clubHome": {
            "id": 700,
            "position": 0,
            "clubName": {
                "id": 4,
                "codeClub": "BRE",
                "name": "Brentford",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fber.png?alt=media&token=e560b331-ef20-424e-b504-38c75a3d8dbc",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Gtech Community Stadium",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FBrentford.jpg?alt=media&token=d0146cbe-9a87-401d-9aa5-08eba115f836",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 4
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 4,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "clubAway": {
            "id": 698,
            "position": 0,
            "clubName": {
                "id": 19,
                "codeClub": "WHU",
                "name": "West Ham United",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fwestham.png?alt=media&token=da8d8cba-4048-447d-8422-c85b738122f4",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "London Stadium",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FWest-Ham.jpg?alt=media&token=736b09c3-a315-4047-baa9-bec8ec4d7e5c",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 19
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 19,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "matchDay": "2023-10-14",
        "matchTime": "12:00",
        "season": {
            "seasonname": "2022/23",
            "champion": null,
            "active": 1,
            "activeUI": 1,
            "id": 33
        },
        "roundmatch": 1,
        "leg": "first",
        "resultClubHome": null,
        "resultClubAway": null,
        "stadiumId": {
            "name": "Gtech Community Stadium",
            "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FBrentford.jpg?alt=media&token=d0146cbe-9a87-401d-9aa5-08eba115f836",
            "active": 1,
            "capacity": null,
            "address": null,
            "pitchSize": null,
            "description": null,
            "id": 4
        },
        "referees": null,
        "active": 1
    },
    {
        "id": 40336,
        "matchCode": null,
        "clubHome": {
            "id": 693,
            "position": 0,
            "clubName": {
                "id": 13,
                "codeClub": "MCI",
                "name": "Manchester City",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fmancity.png?alt=media&token=9e8e344b-186b-4469-83fd-9816277c47d8",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Etihad Stadium",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FMan-City.jpg?alt=media&token=ccb9a5da-942a-427e-ac8e-638200f949af",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 13
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 13,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "clubAway": {
            "id": 710,
            "position": 0,
            "clubName": {
                "id": 47,
                "codeClub": "BHK",
                "name": "Blackpool",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2FBP.png?alt=media&token=145a09c2-8a31-49f4-94a7-5272031b55d8",
                "logo": null,
                "active": null,
                "linkclub": null,
                "stadiumid": {
                    "name": "Seasiders Way, Blackpool, FY1 6JJ",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2Fblackpool-st.jpg?alt=media&token=4fb14835-1a6b-4bbb-b8c6-362543124316",
                    "active": 1,
                    "capacity": "",
                    "address": "",
                    "pitchSize": "",
                    "description": "",
                    "id": 69
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 47,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "matchDay": "2023-10-14",
        "matchTime": "22:00",
        "season": {
            "seasonname": "2022/23",
            "champion": null,
            "active": 1,
            "activeUI": 1,
            "id": 33
        },
        "roundmatch": 1,
        "leg": "first",
        "resultClubHome": null,
        "resultClubAway": null,
        "stadiumId": {
            "name": "Etihad Stadium",
            "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FMan-City.jpg?alt=media&token=ccb9a5da-942a-427e-ac8e-638200f949af",
            "active": 1,
            "capacity": null,
            "address": null,
            "pitchSize": null,
            "description": null,
            "id": 13
        },
        "referees": null,
        "active": 1
    },
    {
        "id": 40337,
        "matchCode": null,
        "clubHome": {
            "id": 694,
            "position": 0,
            "clubName": {
                "id": 14,
                "codeClub": "MUN",
                "name": "Manchester United",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fmachesterunited.png?alt=media&token=38f15dba-ce1f-4126-ae8d-45e3a5a6299d",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Old Trafford",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FMan-United.jpg?alt=media&token=887e0042-8135-4c22-a8d6-bd5abadd638a",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 14
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 14,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "clubAway": {
            "id": 704,
            "position": 0,
            "clubName": {
                "id": 2,
                "codeClub": "ARS",
                "name": "Arsenal",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fasen.png?alt=media&token=dd0986bf-bfc4-4cd8-b924-127d577083cc",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Emirates Stadium",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FArsenal.jpg?alt=media&token=f57dd1c3-9f81-4a78-8bf6-f4c97ac8dbc3",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 2
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 2,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "matchDay": "2023-10-15",
        "matchTime": "21:00",
        "season": {
            "seasonname": "2022/23",
            "champion": null,
            "active": 1,
            "activeUI": 1,
            "id": 33
        },
        "roundmatch": 1,
        "leg": "first",
        "resultClubHome": null,
        "resultClubAway": null,
        "stadiumId": {
            "name": "Old Trafford",
            "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FMan-United.jpg?alt=media&token=887e0042-8135-4c22-a8d6-bd5abadd638a",
            "active": 1,
            "capacity": null,
            "address": null,
            "pitchSize": null,
            "description": null,
            "id": 14
        },
        "referees": null,
        "active": 1
    },
    {
        "id": 40339,
        "matchCode": null,
        "clubHome": {
            "id": 705,
            "position": 0,
            "clubName": {
                "id": 3,
                "codeClub": "AVL",
                "name": "Aston Villa",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fav.png?alt=media&token=0b142056-468d-4bd4-85d4-6860829aa053",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Villa Park",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FAston-Villa.jpg?alt=media&token=dcf24c07-df5e-4515-936b-548ff1cc43b6",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 3
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 3,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "clubAway": {
            "id": 708,
            "position": 0,
            "clubName": {
                "id": 12,
                "codeClub": "LIV",
                "name": "Liverpool",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fliv.png?alt=media&token=72118342-df8e-47e9-973f-9979f322dc75",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Anfield",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FLiverpool.jpg?alt=media&token=e1256f6c-ca52-403c-beea-1d624925999b",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 12
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 12,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "matchDay": "2023-10-28",
        "matchTime": "12:00",
        "season": {
            "seasonname": "2022/23",
            "champion": null,
            "active": 1,
            "activeUI": 1,
            "id": 33
        },
        "roundmatch": 1,
        "leg": "first",
        "resultClubHome": null,
        "resultClubAway": null,
        "stadiumId": {
            "name": "Villa Park",
            "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FAston-Villa.jpg?alt=media&token=dcf24c07-df5e-4515-936b-548ff1cc43b6",
            "active": 1,
            "capacity": null,
            "address": null,
            "pitchSize": null,
            "description": null,
            "id": 3
        },
        "referees": null,
        "active": 1
    },
    {
        "id": 40340,
        "matchCode": null,
        "clubHome": {
            "id": 707,
            "position": 0,
            "clubName": {
                "id": 9,
                "codeClub": "FUL",
                "name": "Fulham",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Ffullham.png?alt=media&token=dbb4af84-8c50-4dc9-9468-8e6acd0fe191",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Craven Cottage",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FMan-United.jpg?alt=media&token=20665265-b696-4e90-91a3-5fa1c77c7117",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 9
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 9,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "clubAway": {
            "id": 703,
            "position": 0,
            "clubName": {
                "id": 10,
                "codeClub": "LEE",
                "name": "Leeds United",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fleed.png?alt=media&token=f7ce1b60-ad36-405a-8b58-96282ad1f4d6",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "Elland Road",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2Fhuyndai.jpg?alt=media&token=8f983420-7ef4-460d-981c-234f6e4b182e",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 10
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 10,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "matchDay": "2023-10-28",
        "matchTime": "12:00",
        "season": {
            "seasonname": "2022/23",
            "champion": null,
            "active": 1,
            "activeUI": 1,
            "id": 33
        },
        "roundmatch": 1,
        "leg": "first",
        "resultClubHome": null,
        "resultClubAway": null,
        "stadiumId": {
            "name": "Craven Cottage",
            "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FMan-United.jpg?alt=media&token=20665265-b696-4e90-91a3-5fa1c77c7117",
            "active": 1,
            "capacity": null,
            "address": null,
            "pitchSize": null,
            "description": null,
            "id": 9
        },
        "referees": null,
        "active": 1
    },
    {
        "id": 40346,
        "matchCode": null,
        "clubHome": {
            "id": 710,
            "position": 0,
            "clubName": {
                "id": 47,
                "codeClub": "BHK",
                "name": "Blackpool",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2FBP.png?alt=media&token=145a09c2-8a31-49f4-94a7-5272031b55d8",
                "logo": null,
                "active": null,
                "linkclub": null,
                "stadiumid": {
                    "name": "Seasiders Way, Blackpool, FY1 6JJ",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2Fblackpool-st.jpg?alt=media&token=4fb14835-1a6b-4bbb-b8c6-362543124316",
                    "active": 1,
                    "capacity": "",
                    "address": "",
                    "pitchSize": "",
                    "description": "",
                    "id": 69
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 47,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "clubAway": {
            "id": 699,
            "position": 0,
            "clubName": {
                "id": 15,
                "codeClub": "NEW",
                "name": "Newcastle United",
                "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/logo%2Fnewcastle.png?alt=media&token=6bafa6f8-b79c-401d-bac3-231485e74cb5",
                "logo": null,
                "active": 0,
                "linkclub": null,
                "stadiumid": {
                    "name": "St. James Park",
                    "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2FNewcastle.jpg?alt=media&token=2a9fd582-7aaa-46cc-847f-689c55813d3f",
                    "active": 1,
                    "capacity": null,
                    "address": null,
                    "pitchSize": null,
                    "description": null,
                    "id": 15
                }
            },
            "played": null,
            "won": 0,
            "draw": 0,
            "lose": 0,
            "points": 0,
            "nextmatch": null,
            "season": 33,
            "clubid": 15,
            "active": 1,
            "gd": 0,
            "ga": 0,
            "gf": 0
        },
        "matchDay": "2023-11-09",
        "matchTime": "14:00",
        "season": {
            "seasonname": "2022/23",
            "champion": null,
            "active": 1,
            "activeUI": 1,
            "id": 33
        },
        "roundmatch": 2,
        "leg": "first",
        "resultClubHome": null,
        "resultClubAway": null,
        "stadiumId": {
            "name": "Seasiders Way, Blackpool, FY1 6JJ",
            "image": "https://firebasestorage.googleapis.com/v0/b/lmproject-538b3.appspot.com/o/images%2Fblackpool-st.jpg?alt=media&token=4fb14835-1a6b-4bbb-b8c6-362543124316",
            "active": 1,
            "capacity": "",
            "address": "",
            "pitchSize": "",
            "description": "",
            "id": 69
        },
        "referees": null,
        "active": 1
    }
]""";
